# Workflow for creating and uploading builds as artifacts

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v2

      - name: Install node packages
        run: npm install

      - name: building the extension
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with: 
          name: cba-build
          path: cba.zip
