name: Tests MV3

on: 
 - push

jobs:
  run-puppeteer:
    name: Run tests MV3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2

    - name: Prepare dependencies
      run: sudo apt-get install xvfb && npm install

    - name: Run linters
      run: npm run lint

    - name: Run tests MV3
      run: MV3=1 xvfb-run npm test
